on: [push, pull_request]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
