on:
  release:
    types:
      - published

name: Upload Release Assets

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name }}

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    env:
      GOTOOLCHAIN: local
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26.x"
      - name: Build binaries
        run: |
          make package
      - name: Calculate hashes
        run: |
          cd bin
          for f in canary_*; do
              shasum -a 256 "$f" > "$f".sha256sum;
          done
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd bin
          tag_name="${GITHUB_REF##*/}"
          gh release upload "$tag_name" canary_*
